const zoneData={lights:["OR Lights","OR lights help the surgical team see clearly while keeping the room organized.","Visibility helps the team work safely and carefully."],table:["Procedure Table","The procedure table is where the patient is positioned and protected by the surgical team.","Patient positioning is planned and handled by trained professionals."],tray:["Sterile Tray","A sterile tray holds tools and supplies that must stay clean and protected.","Sterile tools should only touch sterile surfaces."],sink:["Scrub Sink","The scrub sink is used for careful hand and arm cleaning before sterile work.","Hand hygiene is one of the first defenses against germs."],ppe:["PPE Station","The PPE station holds protective equipment like masks, caps, gowns, and gloves.","PPE creates a barrier between germs and the sterile area."],monitor:["Monitor","Monitors help the team track patient information during care.","The OR team watches patient safety closely."]};
function selectZone(k){
  const i=zoneData[k];
  document.getElementById("zone-title").textContent=i[0];
  document.getElementById("zone-copy").textContent=i[1];
  document.getElementById("zone-tip").textContent=i[2];

  document.querySelectorAll(".zone-button").forEach(b=>b.classList.toggle("active",b.dataset.zone===k));
  document.querySelectorAll(".or-focus").forEach(item=>item.classList.toggle("show", item.id === "or-" + k));
}
document.querySelectorAll(".zone-button").forEach(el=>el.addEventListener("click",()=>selectZone(el.dataset.zone)));
const fieldData={sterile:["Sterile Field","The sterile field is a protected clean area where sterile tools and supplies are placed.","Sterile items should only touch other sterile items.","sterile-mode"],nonsterile:["Non-Sterile Area","A non-sterile area is not clean enough to touch sterile tools or supplies.","Non-sterile items must stay away from the sterile field.","nonsterile-mode"],boundary:["Sterile Boundary","The boundary helps the team remember where the protected clean area begins and ends.","Boundaries help prevent accidental contamination.","boundary-mode"],contamination:["Contamination","Contamination means something sterile may have touched something non-sterile or unclean.","If contamination happens, trained staff replace or fix the unsafe item.","contamination-mode"]};
function selectField(k){
  const i=fieldData[k];
  document.getElementById("field-title").textContent=i[0];
  document.getElementById("field-copy").textContent=i[1];
  document.getElementById("field-tip").textContent=i[2];

  document.querySelectorAll(".field-button").forEach(b=>b.classList.toggle("active",b.dataset.field===k));
  document.querySelectorAll(".field-focus").forEach(item=>item.classList.toggle("show", item.id === "field-" + k));
}
document.querySelectorAll(".field-button").forEach(el=>el.addEventListener("click",()=>selectField(el.dataset.field)));
const ppeData={mask:["Mask","A mask helps reduce droplets from the mouth and nose from spreading into the clean area.","Masks are one part of a larger infection-prevention system."],cap:["Cap","A cap helps keep hair contained and away from the clean area.","Covering hair helps reduce shedding into the room."],gown:["Gown","A surgical gown creates a protective barrier over clothing and skin.","Sterile gowns are handled carefully by trained staff."],gloves:["Sterile Gloves","Sterile gloves protect the patient and help keep sterile tools clean.","Gloves must stay in the sterile area once sterile work begins."],hands:["Hand Hygiene","Hand hygiene helps reduce germs before PPE and sterile work.","Clean hands are a basic safety step."]};
function selectPPE(k){const i=ppeData[k];document.getElementById("ppe-title").textContent=i[0];document.getElementById("ppe-copy").textContent=i[1];document.getElementById("ppe-tip").textContent=i[2];document.querySelectorAll(".ppe-button").forEach(b=>b.classList.toggle("active",b.dataset.ppe===k));document.querySelectorAll(".ppe-part").forEach(part=>part.classList.toggle("active",part.dataset.ppe===k));}
document.querySelectorAll(".ppe-button,.ppe-part").forEach(el=>el.addEventListener("click",()=>selectPPE(el.dataset.ppe)));
document.querySelectorAll(".tab").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===btn));document.querySelectorAll(".panel").forEach(p=>p.classList.toggle("active",p.id===btn.dataset.tab));}));
const quiz=[["What does sterile mean in this lesson?",["Kept free from germs as much as possible","Messy","Always colorful","Broken"],"Kept free from germs as much as possible","Sterile means kept as free from germs as possible."],["What is a sterile field?",["A protected clean area","A playground","A lunch table","A type of bone"],"A protected clean area","The sterile field is the protected clean area for sterile supplies."],["Why does PPE matter?",["It creates protective barriers","It makes surgery faster by itself","It replaces hand hygiene","It is only for decoration"],"It creates protective barriers","PPE helps create barriers against germs."],["What should non-sterile items do?",["Stay away from sterile items","Touch sterile tools","Go on the sterile tray","Replace gloves"],"Stay away from sterile items","Non-sterile items should not touch sterile items."],["What should a team do if something sterile becomes contaminated?",["Communicate and fix it safely","Ignore it","Hide it","Use it anyway"],"Communicate and fix it safely","Teams speak up and fix unsafe situations."],["Is this project real medical instruction?",["No, it is educational only","Yes, it teaches real surgery","Yes, it replaces doctors","Yes, it is for home procedures"],"No, it is educational only","This is a learning model, not medical advice."]];
let q=0;function renderQuiz(){const item=quiz[q];document.getElementById("quiz-number").textContent=q+1;document.getElementById("quiz-question").textContent=item[0];document.getElementById("quiz-feedback").textContent="";document.getElementById("quiz-feedback").className="";const choices=document.getElementById("quiz-choices");choices.innerHTML="";item[1].forEach(choice=>{const btn=document.createElement("button");btn.className="quiz-choice";btn.textContent=choice;btn.onclick=()=>{document.querySelectorAll(".quiz-choice").forEach(x=>x.classList.remove("selected"));btn.classList.add("selected");const ok=choice===item[2];const feedback=document.getElementById("quiz-feedback");feedback.textContent=(ok?"Correct. ":"Not quite. Correct answer: "+item[2]+". ")+item[3];feedback.className=ok?"correct":"wrong";};choices.appendChild(btn);});document.getElementById("next-question").textContent=q===quiz.length-1?"Restart Study Check":"Next Question";}
document.getElementById("next-question").addEventListener("click",()=>{q=(q+1)%quiz.length;renderQuiz();});selectZone("lights");selectField("sterile");selectPPE("mask");renderQuiz();
