const $=id=>document.getElementById(id);
const vocab={epidermis:["Epidermis","The thin outer layer of skin. It protects the body from the outside world."],dermis:["Dermis","The deeper skin layer with blood vessels, nerves, collagen, sweat glands, and hair roots."],hypodermis:["Hypodermis","A deeper fatty layer that helps cushion and insulate the body."],platelets:["Platelets","Tiny blood pieces that help form clots to slow bleeding."],fibroblast:["Fibroblast","A repair cell that makes collagen during wound healing."],collagen:["Collagen","A strong protein that gives skin structure and helps wounds become stronger as they heal."]};
const wounds=[["scrape","Scrape / abrasion","A shallow surface injury. The outer skin layer is damaged, but deeper layers may be okay.","Is this shallow, deep, bleeding, dirty, or at risk for infection?"],["laceration","Laceration / cut","A cut where skin edges separate. Doctors think about depth, bleeding, cleanliness, and whether closure is needed.","Are the wound edges separated and does it need careful closure?"],["puncture","Puncture wound","A small opening that may go deeper than it looks. Doctors worry about hidden depth and infection risk.","Could a small surface opening hide deeper injury?"],["dirty","Dirty wound","A wound with dirt or contamination. Doctors think carefully about cleaning and infection prevention.","Does this need extra cleaning and infection-risk thinking?"]];
const repair=[["Sterile Gloves","🧤","gloved","Step 1: Sterile gloves","Drag Sterile Gloves to the model. Clean hands and gloves help reduce germ spread."],["Sterile Wash","💧","cleaned","Step 2: Clean the wound","Drag Sterile Wash to the model. Cleaning helps remove germs and debris in this learning model."],["Gauze Pressure","🧻","gauze","Step 3: Control bleeding","Drag Gauze Pressure to the wound. Pressure helps slow bleeding in this simplified model."],["Suture Kit","🧵","sutured","Step 4: Close wound edges","Drag Suture Kit to the wound. Sutures hold wound edges together in this simulation."],["Bandage","🩹","bandaged","Step 5: Protect the repair","Drag Bandage to the wound. A dressing protects the area while healing starts."],["Follow-up Plan","📋","followup","Step 6: Plan follow-up","Drag Follow-up Plan to the model. Doctors watch for healing and infection signs."]];
const stages=[["1. Hemostasis","Platelets help form a clot to slow bleeding.","Platelets and clotting proteins help make a temporary seal."],["2. Inflammation","Immune cells arrive to clean the area and protect against germs.","White blood cells help clean and defend the wound."],["3. Proliferation","Fibroblasts make collagen and new tissue starts filling the wound.","Fibroblasts make collagen, which strengthens the repair."],["4. Remodeling","Collagen reorganizes and the scar slowly becomes stronger over time.","Collagen is remodeled so the repair becomes stronger."]];
const quiz=[["What is the epidermis?",["The outer protective skin layer","A bone cell","A heart chamber","A type of cast"],"The outer protective skin layer","The epidermis is the outer layer of skin."],["What do platelets help do?",["Form a clot","Build a cast","Move bones","Make nerves fire"],"Form a clot","Platelets help slow bleeding by forming clots."],["Which cell makes collagen?",["Fibroblast","Osteoclast","Neuron","Red blood cell"],"Fibroblast","Fibroblasts make collagen during wound repair."],["Why does cleanliness matter in wound care?",["To reduce germ spread and infection risk","To make the room colorful","To make tools heavier","To skip healing"],"To reduce germ spread and infection risk","Clean technique helps reduce infection risk."],["What do sutures do in this model?",["Hold wound edges together","Make blood disappear forever","Replace skin layers","Act like X-rays"],"Hold wound edges together","Sutures can hold wound edges together while healing begins."],["Why is this lab educational only?",["Real wounds need real clinicians","Websites can do surgery","Games replace hospitals","Bandages are magic"],"Real wounds need real clinicians","This lab teaches ideas, but real wounds need trained medical professionals."]];
let wound=wounds[0], step=0, dragging=null, stage=0, q=0;
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".panel").forEach(p=>p.classList.toggle("active",p.id===b.dataset.tab));});
document.querySelectorAll("[data-term]").forEach(b=>b.onclick=()=>{const v=vocab[b.dataset.term];$("vocab-title").textContent=v[0];$("vocab-copy").textContent=v[1];});
document.querySelectorAll(".next").forEach(b=>b.onclick=()=>{const t=document.querySelector(`.tab[data-tab="${b.dataset.next}"]`);if(t){t.click();scrollTo({top:0,behavior:"smooth"});}});
function renderWounds(){const box=$("wound-buttons");box.innerHTML="";wounds.forEach(w=>{const b=document.createElement("button");b.className="choice "+(w[0]===wound[0]?"active":"");b.textContent=w[1];b.onclick=()=>{wound=w;$("wound-view").className="wound-view "+w[0];$("wound-title").textContent=w[1];$("wound-copy").textContent=w[2];$("wound-question").textContent=w[3];renderWounds()};box.appendChild(b)})}
function renderRepair(){const s=repair[step];$("step-title").textContent=s?s[3]:"Repair path complete";$("step-copy").textContent=s?s[4]:"You finished the simplified repair path. Now study how skin heals.";const list=$("step-list");list.innerHTML="";repair.forEach((r,i)=>{const d=document.createElement("div");d.className="care-step "+(i<step?"done":i===step?"active":"");d.textContent=(i+1)+". "+r[0];list.appendChild(d)});const tray=$("tool-tray");tray.innerHTML="";repair.forEach((r,i)=>{const t=document.createElement("div");t.className="tool "+(i!==step?"inactive":"");t.dataset.index=i;t.innerHTML=`<span class="tool-icon">${r[1]}</span><strong>${r[0]}</strong><small>${i<step?"Done":i===step?"Use now":"Later"}</small>`;t.addEventListener("pointerdown",startDrag);tray.appendChild(t)});const model=$("repair-model");model.className="repair-model";repair.forEach((r,i)=>{if(i<step)model.classList.add(r[2])});updateProgress()}
function startDrag(e){const src=e.currentTarget;if(src.classList.contains("inactive"))return;e.preventDefault();dragging={source:src,index:Number(src.dataset.index),parent:src.parentElement,next:src.nextSibling};src.classList.add("dragging");document.body.appendChild(src);moveDrag(e)}
function moveDrag(e){if(!dragging)return;dragging.source.style.left=e.clientX+"px";dragging.source.style.top=e.clientY+"px";dragging.source.style.display="none";const target=document.elementFromPoint(e.clientX,e.clientY);dragging.source.style.display="";$("repair-model").classList.toggle("ready",!!(target&&target.closest&&target.closest("#repair-model")))}
function endDrag(e){if(!dragging)return;dragging.source.style.display="none";const target=document.elementFromPoint(e.clientX,e.clientY);dragging.source.style.display="";const ok=target&&target.closest&&target.closest("#repair-model")&&dragging.index===step;if(ok){$("effect").innerHTML='<div class="success">✓</div>';setTimeout(()=>$("effect").innerHTML="",700);step++;$("feedback").textContent=step>=repair.length?"Repair path complete. Now study the healing timeline.":"Good. Move to the next repair step.";renderRepair()}else{$("repair-model").classList.add("wrong");$("feedback").textContent="Try dragging the current step's tool onto the wound model.";setTimeout(()=>$("repair-model").classList.remove("wrong"),400)}dragging.source.classList.remove("dragging");dragging.source.style.left="";dragging.source.style.top="";if(dragging.next)dragging.parent.insertBefore(dragging.source,dragging.next);else dragging.parent.appendChild(dragging.source);$("repair-model").classList.remove("ready");dragging=null}
window.addEventListener("pointermove",moveDrag);window.addEventListener("pointerup",endDrag);
function updateProgress(){const pct=Math.round(step/repair.length*100);$("progress-title").textContent=pct+"%";$("progress-fill").style.width=pct+"%";if(pct===0)$("feedback").textContent="Start with sterile gloves.";if(pct===100)$("feedback").textContent="Repair path complete. Now study the healing timeline."}
$("reset").onclick=()=>{step=0;renderRepair()};
function renderTimeline(){const box=$("timeline-buttons");box.innerHTML="";stages.forEach((s,i)=>{const b=document.createElement("button");b.className="timeline-button "+(i===stage?"active":"");b.textContent=s[0];b.onclick=()=>{stage=i;$("healing-art").className="healing-art stage"+i;$("stage-title").textContent=s[0];$("stage-copy").textContent=s[1];$("stage-note").textContent=s[2];renderTimeline()};box.appendChild(b)})}
function renderQuiz(){const item=quiz[q];$("quiz-number").textContent=q+1;$("quiz-question").textContent=item[0];$("quiz-feedback").textContent="";$("quiz-feedback").className="";$("quiz-choices").innerHTML="";item[1].forEach(choice=>{const b=document.createElement("button");b.className="quiz-choice";b.textContent=choice;b.onclick=()=>{document.querySelectorAll(".quiz-choice").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");const ok=choice===item[2];$("quiz-feedback").textContent=(ok?"Correct! ":"Not quite. Correct answer: "+item[2]+". ")+item[3];$("quiz-feedback").className=ok?"correct":"wrong"};$("quiz-choices").appendChild(b)});$("next-question").textContent=q===quiz.length-1?"Restart Quiz":"Next Question"}
$("next-question").onclick=()=>{q=(q+1)%quiz.length;renderQuiz()};
renderWounds();renderRepair();renderTimeline();renderQuiz();
